### ISSUE TITLE
Install info is incorrect

### ISSUE THREAD

**Issue by axelsimon** [taltman/cloudbleed-browser-scan#1]
Hi, trying to install following the README.md's install method:

> [axel@laptop:~/Software/tmp] $ git clone --recursive git@github.com:taltman/cloudbleed-browser-scan.git
> Cloning into 'cloudbleed-browser-scan'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rightsand the repository exists.

cloning using the https address works fine (`git clone https://github.com/taltman/cloudbleed-browser-scan`), however the `.gitmodules` file uses `url = git@github.com:pirate/sites-using-cloudflare.git` which runs into the same problem.

As my git-fu is weak, I haven't yet worked out how to get git to recursively pull the `sites-using-cloudflare` using the https protocol (switching the url to `url = https://github.com/pirate/sites-using-cloudflare` is easy enough).

In any case, thanks for the tool 😃

**Comment by taltman** [comment]
Hi Axel!

Thanks for catching that! My code was mistakenly assuming that others would have GitHub access as well, which is bogus. I've fixed it now. I'm able to recursively clone from the HTTPS-fetched repo, and it pulls in everything correctly. Thanks for catching that! Please feel free to pull again. If it doesn't work, feel free to reopen this ticket. Have a great day!
